### ISSUE TITLE
Default table name is affected by system locale

### ISSUE THREAD

**Issue by faketifosi** [j256/ormlite-core#67]
DatabaseTableConfig.extractTableName(...) is using toLowerCase() without specific locale.
Languages such as Turkish would result in unexpected name.

**Comment by j256** [comment]
`String.toLowerCase()` uses the default locale which should be set via `Locale.setDefault(...)` appropriately right?

**Comment by faketifosi** [comment]
For the use case such like Android apps, we must respect the default locale which set by user.

Thanks

**Comment by j256** [comment]
Isn't that what the code is doing?  `String.toLowerCase()` uses the default locale that is set by the user, right?

**Comment by faketifosi** [comment]
The table name should be deterministic, must **not** be affected by user's locale.

**Comment by j256** [comment]
Huh?  Then I'd argue that the user should be using ASCII characters for the name of the table and not some special characters which may not be handled by the database.

I'm going to close this but feel free to start a discussion on one of the ormlite mailing lists.

**Comment by JackieKu** [comment]
As an Android app developer, I am using only ASCII characters for the class name, but even some ASCII characters could become non-ASCII characters by calling .toLowerCase(), if the default locale is Turkey. (See "Be wary of the default locale": http://developer.android.com/reference/java/util/Locale.html#default_locale)

I think the table name should be controlled and deterministic for the developer, but not the the app's users, who can control the default locale of their phones.

**Comment by j256** [comment]
Hrm.  Ok.  I can see you point.  But what is the solution?  If I force a english locale, I'm not sure that will work either or at least it might break backwards compatibility.  Maybe folks should be encouraged to use the `@DatabaseTable(tableName = "somethingalllowercase")` ?

**Comment by michelzanini** [comment]
Hi @j256. This is also happening on QueryBuilder.orderBy(). My order by column is not being recognized when the language of the device is Turkish.

`Fatal Exception: java.lang.IllegalArgumentException: You should use columnName 'providedId' for table trip instead of fieldName 'providedId'
       at com.j256.ormlite.table.TableInfo.getFieldTypeByColumnName(TableInfo.java:151)
       at com.j256.ormlite.stmt.StatementBuilder.verifyColumnName(StatementBuilder.java:190)
       at com.j256.ormlite.stmt.QueryBuilder.orderBy(QueryBuilder.java:193)`

Like mentioned above, you NEED to do a lowerCase that is not affected by user locale!
You will never want tables and columns to change depending on User language!

Thanks.

**Comment by michelzanini** [comment]
Please reopen this issue, since it's NOT fixed.

**Comment by edoardotognoni** [comment]
+1

**Comment by j256** [comment]
Ok.  This has been fixed now in trunk.  See:  https://github.com/j256/ormlite-core/commit/8ccc75d7479f33ea99f8b0a3bed3b934ecdd757c#diff-0e636e7f4a0027e6ebdd3278686392e1

**Comment by chihung93** [comment]
related #108

**Comment by virtumedia** [comment]
I see that this fix has now been merged. Is there a new version we can access with this fix? Maven still shows 5.0 as the latest.

**Comment by j256** [comment]
FYI: 5.1 was released on 2/29/2018.

**Comment by virtumedia** [comment]
Many thanks!

----- Original Message -----
